name: Build docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish docker image to Docker Hub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      env:
        GITHUB_TAG: 0.1.0
      with:
        name: nikitavbv/pg-backup-to-gcs
        registry: docker.io
        username: nikitavbv
        password: ${{ secrets.docker_hub_token }}
        tagging: true
